E_commerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_authentication.urls', namespace='user_authentication')),
    path('buyer/', include('buyer.urls', namespace='buyer')),
    path('seller/', include('seller.urls', namespace='seller'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyer/urls.py
from django.urls import path
from .views import cart_views, checkout_views, product_views

app_name = 'buyer'

urlpatterns = [
    path('', product_views.BuyerDashboard.as_view(), name='dashboard'),
    path('product_details/<int:pk>', product_views.ProductDetailView.as_view(), name='product_details'),
    path('cart', cart_views.CartItems.as_view(), name='cart'),
    path('add_to_cart/<int:id>', cart_views.add_to_cart, name='add_to_cart'),
    path('delete/<int:pk>', cart_views.RemoveFromCart.as_view(), name='delete'),
    path('checkout_logic', checkout_views.checkout_logic, name='checkout_logic'),
    path('checkout_form', checkout_views.CheckoutDetailsForm.as_view(), name='checkout_form'),
    path('confirmation', checkout_views.ConfirmationView.as_view(), name='confirmation'),
    path('success', checkout_views.SuccessView.as_view(), name='success')
]

seller/urls.py
from django.urls import path
from . import views

app_name = 'seller'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('product_detail/<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('add_product', views.AddProductForm.as_view(), name='add_product'),
    path('delete/<int:pk>', views.DeleteProduct.as_view(), name='delete'),
    path('update/<int:pk>', views.UpdateProduct.as_view(), name='update')
]

user_authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'user_authentication'
# Defining url_patterns for user authentication
urlpatterns = [
    path('', views.authentication, name='authentication'),
    path('login', views.CustomLoginView.as_view(), name='login'),
    path('homepage', views.homepage, name='homepage'),
    path('register', views.RegisterForm.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout')

]

seller/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class ProductModel(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=80, null=False)
    product_description = models.CharField(max_length=500)
    product_price = models.IntegerField(null=False)
    product_image = models.ImageField(upload_to='product_images/')
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.product_name

seller/forms.py
from django import forms
from .models import ProductModel


class ProductForm(forms.ModelForm):
    product_name = forms.CharField(label='Product Name', max_length=100, required=True)
    product_description = forms.CharField(label='Product Description', max_length=500, required=False,
                                          widget=forms.Textarea)
    product_price = forms.IntegerField(label='Price', required=True)
    product_image = forms.ImageField(label='Image')

    class Meta:
        model = ProductModel
        fields = ['product_name', 'product_description', 'product_price', 'product_image']

seller/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView, UpdateView
from django.views.generic.edit import FormView
from .models import ProductModel
from .forms import ProductForm
from django.contrib.auth.mixins import LoginRequiredMixin


# This View handles the seller dashboard
class DashboardView(LoginRequiredMixin, ListView):
    template_name = 'seller/dashboard.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return ProductModel.objects.filter(user=self.request.user)


# This View handles the detail page
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = ProductModel
    template_name = 'seller/details.html'


# This View handles the add_product_page
class AddProductForm(LoginRequiredMixin, FormView):
    form_class = ProductForm
    template_name = 'seller/add_product.html'

    def form_valid(self, form):
        data = form.cleaned_data
        user = self.request.user
        product = ProductModel(
            user=user,
            product_name=data['product_name'],
            product_price=data['product_price'],
            product_description=data['product_description'],
            product_image=data['product_image']
        )
        product.save()
        return HttpResponseRedirect(reverse('seller:dashboard'))


class DeleteProduct(DeleteView):
    model = ProductModel
    template_name = 'seller/confirm_delete.html'
    success_url = reverse_lazy('seller:dashboard')


class UpdateProduct(UpdateView):
    template_name = 'seller/update_product.html'
    model = ProductModel

    def get_success_url(self):
        return reverse_lazy('seller:product_detail', args=(self.object.id,))

    def get_form_class(self):
        return ProductForm

seller/templates/seller/add_product.html
{% extends 'layout.html' %}
{% block head %}
<title>Add product</title>
{% endblock %}

{% block body %}
<h1>Add product</h1>
<fieldset>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</fieldset>
{% endblock %}

seller/templates/seller/confirm_delete.html
{% extends 'generic_delete_page.html' %}
{% block links %}
<br>
 <a href="{% url 'seller:product_detail' pk=object.id %}">
        <button>Cancel</button>
    </a>
{% endblock %}

seller/templates/seller/dashboard.html
{% extends 'layout.html' %}

{% block head %}
<title>Seller Dashboard</title>
{% endblock %}

{% block body %}

{% if product_list %}
<h1>Your product list is as under</h1>
{% for product in product_list %}
<ul>
    <li><a href="{% url 'seller:product_detail' pk=product.id %}">
        {{product.product_name}}
    </a>
    </li>
</ul>
{% endfor %}
Click here to add a new one:
<a href="{% url 'seller:add_product' %}">
    <button>Add Product</button>
</a>

{% else %}
<h2>You have not published any products</h2>
<div>Click here to add a new one:
    <a href="{% url 'seller:add_product' %}">
        <button>Add Product</button>
    </a>
</div>
{% endif %}
<br>
<br>
<br>
<div>
    <a href="{% url 'user_authentication:logout' %}">
        <button>Log Out</button>
    </a>

    <a href="{% url 'user_authentication:homepage' %}">
        <button>Switch</button>
    </a>
</div>

{% endblock %}

seller/templates/seller/details.html
{% extends 'base_details_for_product_view.html' %}

{% block links %}
<div>
    <a href="{% url 'seller:dashboard' %}">
        <button>Homepage</button>
    </a>
    <a href="{% url 'seller:update' pk=object.id %}">
        <button>Update</button>
    </a>

    <a href="{% url 'seller:delete' pk=object.id %}">
        <button>Delete</button>
    </a>


</div>
{% endblock %}

seller/templates/seller/update_product.html
{% extends 'layout.html' %}
{% block head %}
<title>Add product</title>
{% endblock %}

{% block body %}
<h1>Update product</h1>
<!-- Form to update the product !-->>
<fieldset>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</fieldset>
{% endblock %}