E_commerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_authentication.urls', namespace='user_authentication')),
    path('buyer/', include('buyer.urls', namespace='buyer')),
    path('seller/', include('seller.urls', namespace='seller'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyer/urls.py
from django.urls import path
from .views import cart_views, checkout_views, product_views

app_name = 'buyer'

urlpatterns = [
    path('', product_views.BuyerDashboard.as_view(), name='dashboard'),
    path('product_details/<int:pk>', product_views.ProductDetailView.as_view(), name='product_details'),
    path('cart', cart_views.CartItems.as_view(), name='cart'),
    path('add_to_cart/<int:id>', cart_views.add_to_cart, name='add_to_cart'),
    path('delete/<int:pk>', cart_views.RemoveFromCart.as_view(), name='delete'),
    path('checkout_logic', checkout_views.checkout_logic, name='checkout_logic'),
    path('checkout_form', checkout_views.CheckoutDetailsForm.as_view(), name='checkout_form'),
    path('confirmation', checkout_views.ConfirmationView.as_view(), name='confirmation'),
    path('success', checkout_views.SuccessView.as_view(), name='success')
]

user_authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'user_authentication'
# Defining url_patterns for user authentication
urlpatterns = [
    path('', views.authentication, name='authentication'),
    path('login', views.CustomLoginView.as_view(), name='login'),
    path('homepage', views.homepage, name='homepage'),
    path('register', views.RegisterForm.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout')

]

user_authentication/models.py
from django.db import models

# Create your models here.

user_authentication/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView


# Loads Homepage
def homepage(request):
    return render(request, 'user_authentication/homepage.html')


# Loads user_authentication.html
def authentication(request):
    return render(request, 'user_authentication/user_authentication.html')


# Defining the view for registration
class RegisterForm(FormView):
    template_name = 'user_authentication/registration/register.html'
    form_class = UserCreationForm

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(reverse('user_authentication:login'))


# Defining the view for login
class CustomLoginView(LoginView):
    template_name = 'user_authentication/registration/login.html'

user_authentication/templates/user_authentication/homepage.html
{% extends 'layout.html' %} <!-- extending from layout present in the templates of project directory -->
{% debug %}
{% block head %}
<title>Homepage</title>
{% endblock %}

{% block body %}
<h1>Welcome to this E-Commerce App</h1>
<div>
    <p>If you are a seller,click here:</p>

    <!-- links to the seller dashboard -->
    <a href="{% url 'seller:dashboard'  %}">
        <button>Seller</button>
    </a>
</div>

<div>
    <p>If you are a buyer,click here:</p>

    <!-- links to the seller dashboard -->
    <a href="{% url 'buyer:dashboard' %}">
        <button>Buyer</button>
    </a>
</div>
<br>
<br>
<br>

 <a href="{% url 'user_authentication:logout' %}">
        <button>Log Out</button>
    </a>
{% endblock %}

user_authentication/templates/user_authentication/user_authentication.html
{% extends 'layout.html' %}

{% block head %}
<title>User_authentication</title>
{% endblock %}
{% block body %}
<h1>Welcome!</h1>
<br>

<p>If you have already registered as a buyer or a seller, you can directly log in. No need to register again</p>
 <!-- links to the login path -->
<h3>If you are already registered,click Here to login:</h3>
 <a href="{% url 'user_authentication:login' %}">
        <button>Login</button>
 </a>

<!-- links to the registration path -->
<h3>If you are not registered, click here to register:</h3>
  <a href="{% url 'user_authentication:register' %}">
        <button>Register</button>
    </a>

{% endblock %}