E_commerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_authentication.urls', namespace='user_authentication')),
    path('buyer/', include('buyer.urls', namespace='buyer')),
    path('seller/', include('seller.urls', namespace='seller'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyer/urls.py
from django.urls import path
from .views import cart_views, checkout_views, product_views

app_name = 'buyer'

urlpatterns = [
    path('', product_views.BuyerDashboard.as_view(), name='dashboard'),
    path('product_details/<int:pk>', product_views.ProductDetailView.as_view(), name='product_details'),
    path('cart', cart_views.CartItems.as_view(), name='cart'),
    path('add_to_cart/<int:id>', cart_views.add_to_cart, name='add_to_cart'),
    path('delete/<int:pk>', cart_views.RemoveFromCart.as_view(), name='delete'),
    path('checkout_logic', checkout_views.checkout_logic, name='checkout_logic'),
    path('checkout_form', checkout_views.CheckoutDetailsForm.as_view(), name='checkout_form'),
    path('confirmation', checkout_views.ConfirmationView.as_view(), name='confirmation'),
    path('success', checkout_views.SuccessView.as_view(), name='success')
]

user_authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'user_authentication'
# Defining url_patterns for user authentication
urlpatterns = [
    path('', views.authentication, name='authentication'),
    path('login', views.CustomLoginView.as_view(), name='login'),
    path('homepage', views.homepage, name='homepage'),
    path('register', views.RegisterForm.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout')

]

buyer/models.py
from django.db import models
from django.contrib.auth.models import User
from seller.models import ProductModel


class CartModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)


class ShippingDetails(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, null=False, default='Your name ')
    city = models.CharField(max_length=70, null=False, default='Your city')
    address = models.CharField(max_length=200, null=False, default='Your address')
    email = models.EmailField(default='Your email')

buyer/forms.py
from django import forms
from .models import ShippingDetails


class ShippingForm(forms.ModelForm):
    name = forms.CharField(max_length=150, required=True)
    city = forms.CharField(max_length=70,  required=True)
    address = forms.CharField(max_length=200,  required=True)
    email = forms.EmailField()

    class Meta:
        model = ShippingDetails
        fields = ['name', 'city', 'address', 'email']

buyer/views/cart_views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from buyer.models import CartModel
from django.http import HttpResponseRedirect
from seller.models import ProductModel


# Handling the cart logic
class CartItems(LoginRequiredMixin, ListView):
    template_name = 'buyer/cart.html'
    context_object_name = 'cart_items'

    def get_queryset(self):
        return CartModel.objects.filter(user=self.request.user)

    def calculate_total_price(self):
        total_price = self.get_queryset().aggregate(total_price=Sum('product__product_price'))['total_price']
        return total_price

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_price'] = self.calculate_total_price()
        return context


def add_to_cart(request, id):
    product_instance = ProductModel.objects.get(pk=id)
    cart_item = CartModel.objects.create(product=product_instance, user=request.user)
    cart_item.save()
    return HttpResponseRedirect(reverse('buyer:cart'))


class RemoveFromCart(DeleteView):
    model = CartModel
    template_name = 'buyer/confirm_delete.html'
    success_url = reverse_lazy('buyer:cart')

buyer/views/checkout_views.py
from django.views.generic import TemplateView
from django.shortcuts import reverse,render
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.views.generic import FormView
from buyer.forms import ShippingForm
from buyer.models import ShippingDetails,CartModel


# Handling checkout
def checkout_logic(request):
    if ShippingDetails.objects.filter(user=request.user):
        return HttpResponseRedirect(reverse('buyer:confirmation'))
    else:
        return HttpResponseRedirect(reverse('buyer:checkout_form'))


class CheckoutDetailsForm(FormView):
    template_name = 'buyer/checkout_form.html'
    form_class = ShippingForm

    def form_valid(self, form):
        data = form.cleaned_data
        shipping_details = ShippingDetails(
            user=self.request.user,
            name=data['name'],
            address=data['address'],
            city=data['city'],
            email=data['email']

        )
        shipping_details.save()
        return HttpResponseRedirect(reverse('buyer:confirmation'))


class ConfirmationView(TemplateView):
    template_name = 'buyer/confirm_order.html'


class SuccessView(TemplateView):
    template_name = 'buyer/success.html'

    def get(self, request, *args, **kwargs):
        recipient = ShippingDetails.objects.get(user=request.user)
        recipient_email = recipient.email
        send_order_confirmation_email(recipient_email)
        CartModel.objects.filter(user=self.request.user).delete()
        return render(request, self.template_name)


def send_order_confirmation_email(recipient_email):
    subject = 'Order Confirmation'
    message = 'Thank you for your order!It will be delivered within 5 workiing days'
    from_email = 'danishabbas2004@gmail.com'
    recipient_list = [recipient_email]
    send_mail(subject, message, from_email, recipient_list)

buyer/views/product_views.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from seller.models import ProductModel


# Showing all products to the buyer
class BuyerDashboard(LoginRequiredMixin, ListView):
    template_name = 'buyer/dashboard.html'
    context_object_name = 'all_products'

    def get_queryset(self):
        return ProductModel.objects.all()


# Rendering the detail page for each product
class ProductDetailView(LoginRequiredMixin, DetailView):
    template_name = 'buyer/product_details.html'
    model = ProductModel

buyer/templates/buyer/cart.html
{% extends 'layout.html' %}
{% block head %}
<title>Cart</title>
{% endblock %}

{% block body %}
<h1>Your Cart</h1>
{% if cart_items %}
{% for item in cart_items %}
<ul>
    <li>
        {{item.product.product_name}}:{{item.product.product_price}}
        <a href="{% url 'buyer:delete' pk=item.id %}">
            <button>
                Delete
            </button>
        </a>
    </li>
</ul>
{% endfor %}
{% else %}
<h2>Your cart is empty</h2>
{% endif %}

<h1>Total price: {{total_price}}</h1>

<div>
    <a href="{%url 'buyer:dashboard' %}">
        <button>
            Click Here to go back
        </button>
    </a>

    <a href="{%url 'buyer:checkout_logic' %}">
        <button>
            Checkout
        </button>
    </a>
</div>
{% endblock %}

buyer/templates/buyer/checkout_form.html
{% extends 'layout.html' %}
{% block head %}
<title>Details</title>
{% endblock %}

{% block body %}
<h1>Add Details</h1>
<fieldset>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</fieldset>
{% endblock %}

buyer/templates/buyer/confirm_delete.html
{% extends 'generic_delete_page.html' %}
{% block links %}
<br>
<br>
<a href="{% url 'buyer:cart' %}">
    <button>Cancel</button>
</a>
{% endblock %}

buyer/templates/buyer/confirm_order.html
{% extends 'layout.html' %}
{% block head %}
<title>Confirmation</title>
{% endblock %}

{% block body %}
<h2>We have your details, click here to confirm order:</h2>
<a href="{%url 'buyer:success' %}">
    <button>
    Confirm Order
</button></a>
{% endblock %}

buyer/templates/buyer/dashboard.html
{% extends 'layout.html' %}
{% block body %}
<h1>Welcome!</h1>
<h2>The following items are for sale:</h2>
<h3>
    <div>
        <a href="{% url 'user_authentication:logout' %}">
            <button>Log Out</button>
        </a>

        <a href="{% url 'user_authentication:homepage' %}">
            <button>Switch</button>
        </a>
        <a href="{% url 'buyer:cart' %}"><button>Cart
        </button></a>
    </div>

</h3>
<div class="product-grid">
    {% if all_products %}
    {% for product in all_products %}
    <div class="product-box">
        <a href="{% url 'buyer:product_details' pk=product.id %}">
            <img class="product-image" src="{{ product.product_image.url }}" alt="{{ product.product_name }}">
            <p>{{ product.product_name }}</p>
            <p>Price: ${{ product.product_price }}</p>
        </a>
    </div>
    {% endfor %}
    {% else %}
    <h2>Sellers havent posted anything yet. How about you ask different people to use the app and post things</h2>
    {% endif %}
</div>

{% endblock %}

buyer/templates/buyer/product_details.html
{% extends 'base_details_for_product_view.html' %}

{% block head %}
<title>Product Info</title>
{% endblock %}

{% block links %}
<div>
    <a href="{% url 'buyer:dashboard' %}">
        <button>Homepage</button>
    </a>
    <a href="{% url 'buyer:add_to_cart' id=object.id %}">
        <button>Add to Cart</button>
    </a>
</div>
{% endblock %}

buyer/templates/buyer/success.html
{% extends 'layout.html' %}
{% block head %}
<title>Order Complete</title>
{% endblock %}

{% block body %}
<h1>Your order is confirmed.An email has been sent to you</h1>
<a href="{% url 'buyer:dashboard' %}">
    <button>
        Homepage
    </button>
</a>
{% endblock %}